config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  
  root to: 'pets#index'
  
  resources :pets, only: :index

  resources :jobs do
    resources :jobnegotiations, only: [:index,:create]
  end

  resources :cravings do
    resources :cravingnegotiations, only: [:index,:create]
  end

  resources :mypages do
    resources :calendars
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  with_options presence: true do
    validates :zip, format: { with: /\A\d{3}[-]\d{4}\z/ }
    validates :prefecture_id, numericality: { greater_than: 1 }
    validates :city, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: '全角文字を使用してください' }
    validates :phone, numericality: { only_integer: true }, format: { with: /\A\d{11}\z/ }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :mypage
  has_one :user, through: :mypage
  
  def start_time
    self.vlog_day
  end 
end

app/models/craving.rb
class Craving < ApplicationRecord
  belongs_to :user
  has_one :craving_history
  has_one_attached :craving_picture

  paginates_per 8

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :working_hour
  belongs_to_active_hash :working_time
  belongs_to_active_hash :experience

  with_options presence: true do
    validates :title
    validates :text
    validates :working_date
  end

  with_options presence: true, numericality: { greater_than: 1 } do
    validates :experience_id
    validates :working_hour_id
    validates :working_time_id
  end
end

app/models/craving_history.rb
class CravingHistory < ApplicationRecord
  belongs_to :craving
  has_one :user, through: :craving
end

app/models/cravingnegotiation.rb
class Cravingnegotiation < ApplicationRecord
  belongs_to :craving
  belongs_to :user
  
end

app/models/dog_love.rb
class DogLove < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '犬大好き！動物大好き！' },
    { id: 3, name: '犬は好き！' },
    { id: 4, name: '犬に興味あり！' }
  ]
end

app/models/experience.rb
class Experience < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '飼育経験あり' },
    { id: 3, name: '飼育経験は無いが、遊んだり世話の経験あり' },
    { id: 4, name: '飼育経験無し' }
  ]
end

app/models/job.rb
class Job < ApplicationRecord
  has_one_attached :dog_picture
  belongs_to :user
  has_one    :job_history

  paginates_per 8

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :working_hour
  belongs_to_active_hash :working_time
  belongs_to_active_hash :experience

  with_options presence: true do
    validates :title
    validates :text
    validates :dog_name
    validates :dog_bleed
    validates :dog_age
    validates :working_date
  end

  with_options presence: true, numericality: { greater_than: 1 } do
    validates :working_hour_id
    validates :working_time_id
  end
end

app/models/job_history.rb
class JobHistory < ApplicationRecord
  belongs_to :job
  has_one :user, through: :job
end

app/models/jobnegotiation.rb
class Jobnegotiation < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/mypage.rb
class Mypage < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :mypage_picture
  has_one :calendar

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :dog_love

  with_options presence: true do
    validates :text
    validates :dog_love_id, numericality: { greater_than: 1 }
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福島県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }

  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one  :mypage
  has_many :jobs
  has_many :cravings
  has_one  :address
  has_many :job_histories, through: :jobs
  has_many :craving_histories, through: :cravings
  has_one :calendar, through: :mypage

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: '全角を使用してください' } do
    validates :first_name
    validates :family_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: '全角(カタカナ)を使用してください' } do
    validates :first_kana
    validates :family_kana
  end

  with_options presence: true do
    validates :nickname, length: { maximum: 40 }
    validates :birth
    validates :email, uniqueness: true
  end

  validates :email, format: { with: /@.+/ }

  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'には英字と数字の両方を含めて設定してください' }, on: :create
  validates :password_confirmation, confirmation: true, on: :create
end

app/models/working_hour.rb
class WorkingHour < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '１時間' },
    { id: 3, name: '２時間' },
    { id: 4, name: '３時間' },
    { id: 5, name: 'その他、交渉次第' }
  ]
end

app/models/working_time.rb
class WorkingTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '早朝' },
    { id: 3, name: '昼間' },
    { id: 4, name: '夕方' },
    { id: 5, name: '夜' }
  ]
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_job, only: [:show, :edit, :destroy, :update]

  def index
    @jobs = Job.page(params[:page]).includes(:user).order('created_at DESC')
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def update
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    if @job.destroy
      redirect_to jobs_path
    else
      render :show
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :text, :dog_picture, :dog_name, :dog_bleed, :dog_age, :working_hour_id, :working_date, :working_time_id).merge(user_id: current_user.id)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/cravings_helper.rb
module CravingsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/jobs/edit.html.erb
<header class ="new-head">
  <div class = "left-link">
  <%= link_to image_tag("logo.png", class: "pets-icon"), "/" %>
  </div>
  <div class ="right-link">
  <%= link_to '依頼一覧へ戻る', "/jobs", class: "job-back-btn" %>
  </div>
 </header>

<div class = "job-edit-main">
  <div class = "new-contens">
   <div class = "contens">
    <h2>編集箇所を記載してください</h2>
    <%= form_with model:@job, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
     <%#写真%>
     <div class="img-upload">
      <div class="bold-text">
        ワンちゃんの写真※できるだけ添付してください
      </div>
      <div class="click-upload">
        <%= f.file_field :dog_picture,class:"field" %>
      </div>
     </div>
     <%#写真%>
     <%#title,text%>
     <div class="title-text">
      <div class="bold-text">
        タイトル
        <span class="important-mark">必須</span>
      </div>
      <%= f.text_field :title, class:"field", id:"job-titile", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="job-explain">
        <div class="bold-text">
          アピール文
          <span class="important-mark">必須</span>
        </div>
        <%= f.text_area :text, class:"field", id:"job-text", placeholder:"例）用事があっていつもの時間にお散歩に連れていけないので、よければどなたかお散歩を頼めませんか？等" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
     <%#title,text%>
     <%#犬の情報%>
      <div class="dog-detail">
      <div class="bold-text">ワンちゃんの詳細情報</div>
      <div class="dog-exp">
        <div class="bold-text">
          ワンちゃんの名前
          <span class="important-mark">必須</span>
        </div>
         <%= f.text_field :dog_name, class:"field",id:"dog_name", placeholder:"例）犬太郎等（40文字まで）", maxlength:"40" %>
        <div class="bold-text">
          犬種
          <span class="important-mark">必須</span>
        </div>
         <%= f.text_field :dog_bleed,class:"field", id:"dog_bleed", placeholder:"例）雑種（40文字まで）", maxlength:"40" %>
        <div class="bold-text">
          ワンちゃんの年齢
          <span class="important-mark">必須</span>
        </div>
         約<%= f.number_field :dog_age, class:"field", id:"dog_age"%>歳
      </div>  
    </div>
     <%#犬の情報%>
      <%#仕事の情報%>
      <div class="dog-detail">
      <div class="bold-text">散歩の詳細情報</div>
      <div class="sampo-exp">
        <div class="bold-text">
          どのくらいの時間散歩をして欲しいか
          <span class="important-mark">必須</span>
        </div>
        <%= f.collection_select(:working_hour_id, WorkingHour.all, :id, :name, {}, {class:"field", id:"working_hour"}) %>
        <div class="bold-text">
          希望日時
          <span class="important-mark">必須</span>
        </div>
         <%= f.date_field :working_date, class:"field", id:"working_date" %>
         <div class="bold-text">
          お散歩希望時間帯
          <span class="important-mark">必須</span>
        </div>
        <%= f.collection_select(:working_time_id, WorkingTime.all, :id, :name, {}, {class:"field", id:"working_time"}) %>
     </div>
    </div>
     <%#仕事の情報%>
     <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "お散歩依頼変更を投稿する" ,class:"sampo-btn" %>
    </div>
    <%# /下部ボタン %>
   </div>
  <%end%>
</div>
</div>

app/views/jobs/index.html.erb
<%= render "shared/header" %>

<div class = "main">
  <div class = "job-contents">
   <div class = "job-contener">
    <ul class='jobs-lists'>
      <% @jobs.each do |job| %> 
      <li class='job-list'>
       <%#link_to do〜endで要素を同時にリンクにした%>
       <%= link_to "/jobs/#{job.id}" do %>
         <div class='job-img'>
           <%# 交渉ずみならばフラッグをつける表示 %>
            <% if job.job_history.present?%> 
            <%= image_tag "flag.png" , class:"flag"%>
            <%end%>
           <%# //交渉ずみならば表示 %>
           <% if job.dog_picture.present?%>
           <%= image_tag job.dog_picture, class: "job-img" %>
           <% else %>
           <%= image_tag "demo.png", class:"job-img"%>
           <%end%>
         </div>
         <div class='job-info'>
           <div class='dog-name'>
             犬の名前：<%= job.dog_name %>
           </div>
           <div class ="dog-bleed">
             犬種：<%= job.dog_bleed %>
           </div>
            <div class ="dog-date">
             希望日：<%= job.working_date %>
           </div>
           <div class ="dog-prefecture">
             地域：<%= job.user.address.prefecture.name %>
           </div>
         </div>
       <% end %>
       <%#link_to do〜endで要素を同時にリンクにした%>
      </li>
     <% end %>
      <%# 投稿がない場合のダミー %>
      <% if @jobs.length == 0 %>
       <li class='job-list'>
         <%= image_tag "dog_up.jpg", class: "job-img" %>
         <div class='job-info'>
           <h3 class='job-title'>
            散歩依頼ボタンから投稿！
           </h3>
            <div class='dog-name'>
              名前:犬吉
            </div>
            <div class ="dog-bleed">
              犬種:柴犬
            </div>
            <div class ="dog-prefecture">
              地域:沖縄県
            </div>
          </div>
        </li>
      <% end %>
      <%# //投稿がない場合のダミー %>
    </ul>
   </div>
  </div>
<%= paginate @jobs%>  
</div>
<footer>
  <div class ="link-craving">
    <%= link_to "お散歩提供一覧へ",cravings_path,class:"craving-btn" %>
  </div>
</footer>

app/views/jobs/new.html.erb
 <header class ="new-head">
  <div class = "left-link">
  <%= link_to image_tag("logo.png", class: "pets-icon"), "/" %>
  </div>
  <div class ="right-link">
  <%= link_to '依頼一覧へ戻る', "/jobs", class: "job-back-btn " %>
  </div>
 </header>

<div class = "job-new-main">
  <div class = "new-contens">
   <div class = "contens">
    <h2 class="title-top">依頼の内容を記載してください</h2>
    <%= form_with model:@job, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
     <%#写真%>
     <div class="img-upload">
      <div class="bold-text">
        ワンちゃんの写真※できるだけ添付してください
      </div>
      <div class="click-upload">
        <%= f.file_field :dog_picture,class:"field" %>
      </div>
     </div>
     <%#写真%>
     <%#title,text%>
     <div class="title-text">
      <div class="bold-text">
        タイトル
        <span class="important-mark">必須</span>
      </div>
      <%= f.text_field :title, class:"field", id:"job-titile", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="job-explain">
        <div class="bold-text">
          アピール文
          <span class="important-mark">必須</span>
        </div>
        <%= f.text_area :text, class:"ap-field", id:"job-text", placeholder:"例）用事があっていつもの時間にお散歩に連れていけないので、よければどなたかお散歩を頼めませんか？等" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
     <%#title,text%>
     <%#犬の情報%>
      <div class="dog-detail">
      <h3 class="bold-text">ワンちゃんの詳細情報</h3>
      <div class="dog-exp">
        <div class="bold-text">
          ワンちゃんの名前
          <span class="important-mark">必須</span>
        </div>
         <%= f.text_field :dog_name, class:"field",id:"dog_name", placeholder:"例）犬太郎等（40文字まで）", maxlength:"40" %>
        <div class="bold-text">
          犬種
          <span class="important-mark">必須</span>
        </div>
         <%= f.text_field :dog_bleed,class:"field", id:"dog_bleed", placeholder:"例）雑種（40文字まで）", maxlength:"40" %>
        <div class="bold-text">
          ワンちゃんの年齢
          <span class="important-mark">必須</span>
        </div>
         約<%= f.number_field :dog_age, class:"age-field", id:"dog_age"%>歳
      </div>  
    </div>
     <%#犬の情報%>
      <%#仕事の情報%>
      <div class="dog-detail">
      <h3 class="bold-text">散歩の詳細情報</h3>
      <div class="sampo-exp">
        <div class="bold-text">
          どのくらいの時間散歩をして欲しいか
          <span class="important-mark">必須</span>
        </div>
        <%= f.collection_select(:working_hour_id, WorkingHour.all, :id, :name, {}, {class:"field", id:"working_hour"}) %>
        <div class="bold-text">
          希望日時
          <span class="important-mark">必須</span>
        </div>
         <%= f.date_field :working_date, class:"field", id:"working_date"  %>
         <div class="bold-text">
          お散歩希望時間帯
          <span class="important-mark">必須</span>
        </div>
        <%= f.collection_select(:working_time_id, WorkingTime.all, :id, :name, {}, {class:"field", id:"working_time"}) %>
      </div>  
    </div>
     <%#仕事の情報%>
     <%# 下部ボタン %>
    <div class="btn-contents">
      <%= f.submit "散歩依頼を投稿する" ,class:"sampo-btn" %>
    </div>
    <%# /下部ボタン %>
   </div>
  <%end%>
  </div>

 
</div>

app/views/jobs/show.html.erb
<%= render "shared/header" %>
 <div class ="job-show-main">
      <div class = "show-main-up">
       <h2 class ="show-top">お散歩依頼情報</h2>
       <div class = "contents">
          <div class ="show-pic">
            <div class = "show-nickname">
            <%= link_to @job.user.nickname , mypage_path(@job.user.id),class:"job-mypage"%>さんのお散歩依頼です
            </div>
           <%# 交渉ずみならばフラッグをつける表示 %>
             <% if @job.job_history.present?%> 
             <%= image_tag "flag.png",class:"show-flag"%>
             <%end%>
            <%# //交渉ずみならば表示 %>
           <% if @job.dog_picture.present?%>
           <%= image_tag @job.dog_picture, class: "show-craving-pic" %>
           <% else %>
           <%= image_tag "demo.png", class:"show-craving-pic"%>
           <%end%>
          </div>
        </div>
      </div>

      <div class ="job-main-middle">
        <div class = "show-ex">
         <h2 class = "job-sanpo-show">依頼詳細</h2>
        <table ,border = "1" width="80%">
         <tr>
          <th>タイトル</th><td class ="w"><%= @job.title %></td>
          </tr> 
          <tr>
          <th>犬の名前</th><td class = "w"><%= @job.dog_name %></td>
          </tr>
          <tr>
           <th>犬種</th><td class = "w"><%= @job.dog_bleed %></td>
           </tr>
           <tr>
           <th>犬の年齢</th><td class = "w">約<%= @job.dog_age %>歳</td>
           </tr>
         <tr>
         <th>希望散歩時間</th><td class ="w"><%= @job.working_hour.name %></td>
         </tr>
         <tr>
         <th>希望日</th><td class ="w"><%= @job.working_date%></td>
         </tr>
         <tr>
         <th>希望時間帯</th><td class ="w"><%=@job.working_time.name%></td>
         </tr>
         <tr>
         <th>都道府県</th><td class ="w"><%= @job.user.address.prefecture.name %></td>
         </tr>
         <tr>
         <th>市町村</th><td class ="w"><%= @job.user.address.city%></td>
         </tr>
         <tr class ="show-text">
          <th>メッセージ</th>
          <td class ="w"><%= @job.text%></td>
          </tr>
        </table>
        </div>
      </div>
   </div>

<div class = "cr">
 <div class = "cr-offer-btn">
    <% if user_signed_in? && current_user.id == @job.user_id %>
       <%if @job.job_history.present?%>
         <%= link_to '一覧へ戻る', jobs_path , class:'cravings-return-btn' %>
         <%else%>
         <%= link_to '削除', job_path(@job.id) , method: :delete, class:'cr-destroy' %>
         <%= link_to '編集', edit_job_path(@job.id), method: :get, class: "cr-edit" %>
         <%= link_to '一覧へ戻る', jobs_path , class:'cravings-return-btn' %>
       <%end %>
    <%else%>
         <% if @job.job_history == nil  %> 
            <%= link_to '申し込む',  job_jobnegotiations_path(@job.id), method: :get,class:"cr-nego-btn"%> 
            <%= link_to '一覧へ戻る', jobs_path , class:'cravings-return-btn' %>
            <%else%>
            <%= link_to '一覧へ戻る', jobs_path , class:'cravings-return-btn' %>
          <%end %>
    <% end %> 
  </div>
</div>