config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  
  root to: 'pets#index'
  
  resources :pets, only: :index

  resources :jobs do
    resources :jobnegotiations, only: [:index,:create]
  end

  resources :cravings do
    resources :cravingnegotiations, only: [:index,:create]
  end

  resources :mypages do
    resources :calendars
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  with_options presence: true do
    validates :zip, format: { with: /\A\d{3}[-]\d{4}\z/ }
    validates :prefecture_id, numericality: { greater_than: 1 }
    validates :city, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: '全角文字を使用してください' }
    validates :phone, numericality: { only_integer: true }, format: { with: /\A\d{11}\z/ }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :mypage
  has_one :user, through: :mypage
  
  def start_time
    self.vlog_day
  end 
end

app/models/craving.rb
class Craving < ApplicationRecord
  belongs_to :user
  has_one :craving_history
  has_one_attached :craving_picture

  paginates_per 8

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :working_hour
  belongs_to_active_hash :working_time
  belongs_to_active_hash :experience

  with_options presence: true do
    validates :title
    validates :text
    validates :working_date
  end

  with_options presence: true, numericality: { greater_than: 1 } do
    validates :experience_id
    validates :working_hour_id
    validates :working_time_id
  end
end

app/models/craving_history.rb
class CravingHistory < ApplicationRecord
  belongs_to :craving
  has_one :user, through: :craving
end

app/models/cravingnegotiation.rb
class Cravingnegotiation < ApplicationRecord
  belongs_to :craving
  belongs_to :user
  
end

app/models/dog_love.rb
class DogLove < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '犬大好き！動物大好き！' },
    { id: 3, name: '犬は好き！' },
    { id: 4, name: '犬に興味あり！' }
  ]
end

app/models/experience.rb
class Experience < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '飼育経験あり' },
    { id: 3, name: '飼育経験は無いが、遊んだり世話の経験あり' },
    { id: 4, name: '飼育経験無し' }
  ]
end

app/models/job.rb
class Job < ApplicationRecord
  has_one_attached :dog_picture
  belongs_to :user
  has_one    :job_history

  paginates_per 8

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :working_hour
  belongs_to_active_hash :working_time
  belongs_to_active_hash :experience

  with_options presence: true do
    validates :title
    validates :text
    validates :dog_name
    validates :dog_bleed
    validates :dog_age
    validates :working_date
  end

  with_options presence: true, numericality: { greater_than: 1 } do
    validates :working_hour_id
    validates :working_time_id
  end
end

app/models/job_history.rb
class JobHistory < ApplicationRecord
  belongs_to :job
  has_one :user, through: :job
end

app/models/jobnegotiation.rb
class Jobnegotiation < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/mypage.rb
class Mypage < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :mypage_picture
  has_one :calendar

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :dog_love

  with_options presence: true do
    validates :text
    validates :dog_love_id, numericality: { greater_than: 1 }
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福島県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }

  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one  :mypage
  has_many :jobs
  has_many :cravings
  has_one  :address
  has_many :job_histories, through: :jobs
  has_many :craving_histories, through: :cravings
  has_one :calendar, through: :mypage

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: '全角を使用してください' } do
    validates :first_name
    validates :family_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: '全角(カタカナ)を使用してください' } do
    validates :first_kana
    validates :family_kana
  end

  with_options presence: true do
    validates :nickname, length: { maximum: 40 }
    validates :birth
    validates :email, uniqueness: true
  end

  validates :email, format: { with: /@.+/ }

  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'には英字と数字の両方を含めて設定してください' }, on: :create
  validates :password_confirmation, confirmation: true, on: :create
end

app/models/working_hour.rb
class WorkingHour < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '１時間' },
    { id: 3, name: '２時間' },
    { id: 4, name: '３時間' },
    { id: 5, name: 'その他、交渉次第' }
  ]
end

app/models/working_time.rb
class WorkingTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '早朝' },
    { id: 3, name: '昼間' },
    { id: 4, name: '夕方' },
    { id: 5, name: '夜' }
  ]
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @mypage = Mypage.new
  end

  def create
    @mypage = Mypage.new(mypage_params)
    if @mypage.save
      redirect_to pets_path
    else
      redirect_to new_mypage_path
    end
  end

  def show
    user = User.find(params[:id])
    @mypage = user.mypage
    @craving_histories = CravingHistory.includes(:user).order('created_at DESC')
    @job_histories = JobHistory.includes(:user).order('created_at DESC')
    @calendars = Calendar.includes(:user)
  end

  def edit
    @mypage = Mypage.find(params[:id])
  end

  def update
    @mypage = Mypage.find(params[:id])
    if @mypage.update(mypage_params)
      redirect_to pets_path
    else
      render :edit
    end
  end

  private

  def mypage_params
    params.require(:mypage).permit(:dog_love_id, :text, :mypage_picture).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/cravings_helper.rb
module CravingsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/mypages/edit.html.erb
<div class = "my-main">
<h2>変更箇所を記載してください</h2>
<h3><%= current_user.nickname%>さんのマイページ</h3>
  <%= form_with model:@mypage,class: 'mypage-new',id: 'mypage_picture',local: true do |f| %> 
   <%= render 'shared/error_messages', model: f.object %>  
   <div class = "my-contents">
    <div class ="up-content">
         <div class="click-upload">
           <p>
           ※自分をアピールできる写真を載せてみよう。
           </p>
           <div >
            <%= f.file_field :mypage_picture,class:"mypage-pic" %>
           </div>
           <div id="image-list" ></div>
           <%= image_tag @mypage.mypage_picture,class:"my-pic", id: 'image' if @mypage.mypage_picture.present? %> 
         </div>
        <div>
           <div>犬愛をアピールしてね<span class="important-mark">必須</span></div>
           <div >
            <%= f.collection_select(:dog_love_id,DogLove.all, :id, :name, {}, {class:"field", id:"dog_love"}) %>
           </div>
        </div>
        <div>
          <div>自己紹介<span class="important-mark">必須</span></div>
          <div class = "my-text">
          <%= f.text_area :text, class:"intro-field", placeholder:"例) 犬が大好きで幼い頃から飼育経験があります。等", maxlength:"400",autofocus: true %>
          </div>
        </div>
     </div>
    <div class ="btn-mypage">
      <%=f.submit "編集完了" , class:"offer-btn"%>
    </div>
   </div>
  <% end %>
  </div>
  <div class = "foot">
  <%= image_tag "animals_02.png" ,:size =>'800x200', class:"my-foot"%>
  </div>

app/views/mypages/new.html.erb
<div class = "my-main">
<h2>マイページを完成させよう！</h2>
<h3><%= current_user.nickname%>さんのマイページ</h3>
  <%= form_with model:@mypage,class: 'mypage-new',local: true do |f| %> 
   <%= render 'shared/error_messages', model: f.object %>  
   <div class = "my-contents">
    <div class ="up-content">
         <div class="click-upload">
           <p>
           ※自分をアピールできる写真を載せてみよう。
           </p>
           <div class="mypage-pic">
            <%= f.file_field :mypage_picture,class:"mypage-pic" %>
           </div>
         </div>
        <div>
           <div>犬愛をアピールしてね<span class="important-mark">必須</span></div>
           <div >
            <%= f.collection_select(:dog_love_id,DogLove.all, :id, :name, {}, {class:"field", id:"dog_love"}) %>
           </div>
        </div>
        <div>
          <div>自己紹介<span class="important-mark">必須</span></div>
          <div >
          <%= f.text_area :text, class:"intro-field", placeholder:"例) 犬が大好きで幼い頃から飼育経験があります。等", maxlength:"400",autofocus: true %>
          </div>
        </div>
     </div>
    <div class ="btn-mypage">
      <%=f.submit "マイページ登録完了" , class:"offer-btn"%>
    </div>
   </div>
  <% end %>
  </div>
  <div class = "foot">
  <%= image_tag "animals_02.png" ,:size =>'800x200', class:"my-foot"%>
  </div>

app/views/mypages/show.html.erb
  <header class = "my-show-head">
     <div><%= link_to 'お散歩依頼一覧へ', jobs_path , class:'job-btn' %></div>
     <div><%= link_to 'TOPへ', root_path , class:'my-root-btn' %></div>
     <div><%= link_to 'お散歩提供一覧へ', cravings_path , class:'craving-btn' %></div>
  </header>
<div class = "my-show-main">
   <h2 class = "my-nick"><%= @mypage.user.nickname%>さんのページ</h2>
    <div class ="mypage-show-con">
         <div class="my-texts">
             <div class="show-mypage-pic">
               <%if @mypage.mypage_picture.present? %>
               <%= image_tag @mypage.mypage_picture , class:"mypage-show-pic"%>
               <%else%>
               <%= image_tag "logomini.png" , class:"mypage-show-pic"%>
               <%end%>
             </div>
             <div class = "my-love"><%= @mypage.dog_love.name %></div>
         </div>
         <table class = "self-text">
           <th>自己紹介</th>
           <tr>
             <td class = ""><%= @mypage.text%></td>
           </tr>
         </table>
     </div>

      <div class ="history-past">
         <div class = "craving_history_past">
            <ul class ="history_list">
             <li>散歩依頼歴</li>
                <% @craving_histories.each do |craving_history| %> 
                    <%if @mypage.user_id == craving_history.user_id  %>
                 <li class = "my-his">
                     <% @crid = craving_history.craving_id%>
                     <%=Craving.find(@crid).working_date%>
                    <% @mylink = Craving.find(@crid).user_id%>
                     <%=link_to User.find(@mylink).nickname, mypage_path(@mylink), class:"mynego"%>さんに依頼済み</li>
                    <%end%>
                    <%end%>
            </ul>
          </div>
         <div class = "job_history_past">
            <ul class ="history_list">
            <li>散歩実施歴</li>
              <% @job_histories.each do |job_history| %>  
              <%if @mypage.user_id == job_history.user_id %>  
              <li class = "my-his">
                    <% @jobid = job_history.job_id%>
                   <%=Job.find(@jobid).working_date%>
                   <% @mylinkjob = Job.find(@jobid).user_id%>
                    <%=link_to User.find(@mylinkjob).nickname, mypage_path(@mylinkjob), class:"mynego"%>さんのお散歩を実施</li>
              <%end%>  
              <%end%>
            </ul>
        </div>
      </div>
</div>
  <div class ="my-link-btn">
     <% if user_signed_in? && current_user.id == @mypage.user_id %>
     <div><%= link_to "Mypageを編集する" ,"/mypages/#{@mypage.id}/edit", class:"cr-edit"%></div>
     <%end%>
  </div>

<%= link_to "予定を書く" ,new_mypage_calendar_path(@mypage.id)%>

 <%=month_calendar events: @calendars do |date, calendars|%>
   <%= date.day %> 
  <% calendars.each do |calendar| %>
    <div>
      <%=  link_to calendar.title %>
    </div>
    
  <% end %>
<% end %>